# Generated by Django 3.1.3 on 2020-11-03 17:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_howsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='howsec',
            name='how_step',
            field=wagtail.core.fields.StreamField([('h_s', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('icon_image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True),
        ),
    ]
