# Generated by Django 3.1.3 on 2020-11-04 09:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_howsec_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howsec',
            name='how_step',
            field=wagtail.core.fields.StreamField([('h_s', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('icon_image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], null=True),
        ),
        migrations.CreateModel(
            name='ClientsSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=30)),
                ('description', wagtail.core.fields.RichTextField()),
                ('client_icon', wagtail.core.fields.StreamField([('client_icon', wagtail.core.blocks.StructBlock([('icon_image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], null=True)),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_sec', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
