# Generated by Django 3.1.3 on 2020-11-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('home', '0007_auto_20201104_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='information_corner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.informationcorner'),
        ),
    ]
