# Generated by Django 3.1.3 on 2020-11-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('home', '0008_homepage_information_corner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.contactinfo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.partner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='information_corner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.informationcorner'),
        ),
    ]
