# Generated by Django 3.1.3 on 2020-11-04 12:35

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('home', '0009_auto_20201104_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='information_corner',
        ),
        migrations.AddField(
            model_name='homepage',
            name='information_corner',
            field=modelcluster.fields.ParentalManyToManyField(to='mysite.InformationCorner'),
        ),
    ]
