# Generated by Django 3.1.3 on 2020-11-08 18:32

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0011_auto_20201104_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='how_section',
            field=wagtail.core.fields.StreamField([('how_works_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('icon_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('step', wagtail.core.blocks.ListBlock(home.blocks.HowStepBlock))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_section_description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_section_icon_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_section_title',
            field=models.CharField(max_length=255, null=True, verbose_name='How It Work Title'),
        ),
    ]
