import { StyleProp, TextStyle } from 'react-native'

export const main-banner: StyleProp<TextStyle>
export const slide: StyleProp<TextStyle>
export const caption: StyleProp<TextStyle>
export const button-row: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const slick-arrow: StyleProp<TextStyle>
export const slick-prev: StyleProp<TextStyle>
export const slick-next: StyleProp<TextStyle>
export const sub-line: StyleProp<TextStyle>
export const how-it-works: StyleProp<TextStyle>
export const steps: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const title: StyleProp<TextStyle>
export const tooltip-inner: StyleProp<TextStyle>
export const tooltipshow: StyleProp<TextStyle>
export const bs-tooltip-top: StyleProp<TextStyle>
export const arrow: StyleProp<TextStyle>
export const arrow::before: StyleProp<TextStyle>
export const quote-action: StyleProp<TextStyle>
export const quote-sent: StyleProp<TextStyle>
export const quote-accepted: StyleProp<TextStyle>
export const package-ordered: StyleProp<TextStyle>
export const shipped: StyleProp<TextStyle>
export const delivered: StyleProp<TextStyle>
export const clients-trust: StyleProp<TextStyle>
export const inner: StyleProp<TextStyle>
export const account-menu: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const inner-contents: StyleProp<TextStyle>
export const page-title: StyleProp<TextStyle>
export const breadcrumb: StyleProp<TextStyle>
export const breadcrumb-item: StyleProp<TextStyle>
export const inner-wrapper: StyleProp<TextStyle>
export const change-password: StyleProp<TextStyle>
export const form-group: StyleProp<TextStyle>
export const form-control: StyleProp<TextStyle>
export const show-pw: StyleProp<TextStyle>
export const upload-image: StyleProp<TextStyle>
export const profile: StyleProp<TextStyle>
export const action-control: StyleProp<TextStyle>
export const address-btn: StyleProp<TextStyle>
export const address-title: StyleProp<TextStyle>
export const address-wrapper: StyleProp<TextStyle>
export const location: StyleProp<TextStyle>
export const name: StyleProp<TextStyle>
export const num: StyleProp<TextStyle>
export const address: StyleProp<TextStyle>
export const action-btns: StyleProp<TextStyle>
export const btn-red: StyleProp<TextStyle>
export const page-banner: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const side-menu: StyleProp<TextStyle>
export const box: StyleProp<TextStyle>
export const prohibited-items-wrapper: StyleProp<TextStyle>
export const categories: StyleProp<TextStyle>
export const prohibited-items: StyleProp<TextStyle>
export const material-file: StyleProp<TextStyle>
export const contact-us: StyleProp<TextStyle>
export const contact-wrapper: StyleProp<TextStyle>
export const row: StyleProp<TextStyle>
export const details: StyleProp<TextStyle>
export const contact-form: StyleProp<TextStyle>
export const heading: StyleProp<TextStyle>
export const map: StyleProp<TextStyle>
export const account-wrapper: StyleProp<TextStyle>
export const left-side: StyleProp<TextStyle>
export const content: StyleProp<TextStyle>
export const bottom-content: StyleProp<TextStyle>
export const check-item-list: StyleProp<TextStyle>
export const right-side: StyleProp<TextStyle>
export const nav-tabs: StyleProp<TextStyle>
export const category: StyleProp<TextStyle>
export const info: StyleProp<TextStyle>
export const add-product-link: StyleProp<TextStyle>
export const add-more-link: StyleProp<TextStyle>
export const remove-product-link: StyleProp<TextStyle>
export const tab-content: StyleProp<TextStyle>
export const file-upload: StyleProp<TextStyle>
export const dropzone: StyleProp<TextStyle>
export const dz-message: StyleProp<TextStyle>
export const add-images: StyleProp<TextStyle>
export const f-size-12: StyleProp<TextStyle>
export const back-to-page: StyleProp<TextStyle>
export const request-details: StyleProp<TextStyle>
export const section-head: StyleProp<TextStyle>
export const blue: StyleProp<TextStyle>
export const bootstrap-select: StyleProp<TextStyle>
export const dropdown-toggle: StyleProp<TextStyle>
export const filter-option-inner-inner: StyleProp<TextStyle>
export const select-file: StyleProp<TextStyle>
export const product-prices: StyleProp<TextStyle>
export const inline-buttons: StyleProp<TextStyle>
export const request-info: StyleProp<TextStyle>
export const pdf-file: StyleProp<TextStyle>
export const remarks: StyleProp<TextStyle>
export const company-info: StyleProp<TextStyle>
export const images-wrapper: StyleProp<TextStyle>
export const image: StyleProp<TextStyle>
export const terms-condition: StyleProp<TextStyle>
export const order-status: StyleProp<TextStyle>
export const status: StyleProp<TextStyle>
export const item-desc: StyleProp<TextStyle>
export const order-info: StyleProp<TextStyle>
export const quote-info: StyleProp<TextStyle>
export const total: StyleProp<TextStyle>
export const quote: StyleProp<TextStyle>
export const mb-35: StyleProp<TextStyle>
export const mt-50: StyleProp<TextStyle>
export const border-b-grey: StyleProp<TextStyle>
export const success: StyleProp<TextStyle>
export const modal-body: StyleProp<TextStyle>
export const forgot-pass: StyleProp<TextStyle>
export const create-account: StyleProp<TextStyle>
export const attahment-file: StyleProp<TextStyle>
export const business-profile: StyleProp<TextStyle>
export const pagination-wrapper: StyleProp<TextStyle>
export const pagination: StyleProp<TextStyle>
export const page-link: StyleProp<TextStyle>
export const next: StyleProp<TextStyle>
export const page-item: StyleProp<TextStyle>
export const filters: StyleProp<TextStyle>
export const control-label: StyleProp<TextStyle>
export const btn-default: StyleProp<TextStyle>
export const admin-reports: StyleProp<TextStyle>
export const total-count: StyleProp<TextStyle>
export const admin-request: StyleProp<TextStyle>
export const custom-table: StyleProp<TextStyle>
export const trow: StyleProp<TextStyle>
export const table-cell: StyleProp<TextStyle>
export const fc-event: StyleProp<TextStyle>
export const fc-day-grid-event: StyleProp<TextStyle>
export const fc-title: StyleProp<TextStyle>
export const fc-more: StyleProp<TextStyle>
export const shipped-from-origion: StyleProp<TextStyle>
export const tooltip-order-id: StyleProp<TextStyle>
export const tooltip-shipped: StyleProp<TextStyle>
export const tooltip-order-status: StyleProp<TextStyle>
export const toggle-filter-btn: StyleProp<TextStyle>
export const optional-field: StyleProp<TextStyle>
export const remove-optional-fields: StyleProp<TextStyle>
export const add-icon: StyleProp<TextStyle>
export const add-optional-fields: StyleProp<TextStyle>
export const slick-instance: StyleProp<TextStyle>
export const action-links: StyleProp<TextStyle>
export const bootstrap-select>dropdown-toggle:after: StyleProp<TextStyle>
export const col-xl-auto: StyleProp<TextStyle>
export const make-request: StyleProp<TextStyle>
export const extra-space-991: StyleProp<TextStyle>
export const static-label: StyleProp<TextStyle>
export const card-header: StyleProp<TextStyle>
export const card-link: StyleProp<TextStyle>
export const thead: StyleProp<TextStyle>
export const request-date: StyleProp<TextStyle>
export const d-none-lg: StyleProp<TextStyle>
export const col-gap-0: StyleProp<TextStyle>
export const product-link-wrapper: StyleProp<TextStyle>
export const tbody: StyleProp<TextStyle>
export const text-center-sm: StyleProp<TextStyle>
export const steps>div:after: StyleProp<TextStyle>
export const modal: StyleProp<TextStyle>
export const modal-dialog: StyleProp<TextStyle>
export const modal-content: StyleProp<TextStyle>
export const popup-cross-icon: StyleProp<TextStyle>
export const show-on-md: StyleProp<TextStyle>
export const hide-on-md: StyleProp<TextStyle>
export const calender: StyleProp<TextStyle>
export const scroll-wrapper: StyleProp<TextStyle>
export const cardrequest-info>div: StyleProp<TextStyle>
export const mb-15-sm: StyleProp<TextStyle>
export const toggle-filter: StyleProp<TextStyle>
export const content-head: StyleProp<TextStyle>
export const responsive-table-big: StyleProp<TextStyle>
export const trow>: StyleProp<TextStyle>
